[general]
import = [
  #"~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.cache/alacritty_theme.toml"
]

[window]
opacity = 0.9
padding.x = 0
padding.y = 0
decorations = "none"
dynamic_title = true

[font]
size = 12.0
